### ISSUE TITLE
Unnecessary generation of `/sitemap.xml/index.html` when using SSG and i18n-module

### ISSUE THREAD

**Issue by JonathanDoelan** [nuxt-modules/sitemap#230]
I am using `5.1.0` and and also the i18n nuxt module in SSG mode. So when i hit `nuxt generate` it generates the following files as expected:

- `sitemap_index.xml`
- `de-sitemap.xml`
- `en-sitemap.xml`

… but also unexpectedly, it renders:

- `sitemap.xml/index.html`

I don’t want the latter to be rendered. Especially when using the `html-validate` module, it throws an error, because it is no valid html page. It shouldn’t be there imo.

Is there an option to prevent this or is this a bug?

**Comment by harlan-zw** [comment]
I think the is an Nuxt bug will investigate deeper when I have a chance

**Comment by JonathanDoelan** [comment]
Thanks for the quick answer. I have downgraded to `4.4.1` where the bug does not occur …

**Comment by harlan-zw** [comment]
Ah so this is a feature of Nuxt in that when you prerender your site as static, it will turn any redirects into a HTML page that redirects. If these aren't validating then it's probably an upstream bug that should be fixed with the `html-validate` module.

It is valid HTML though so not sure what's going on and not sure if it's worth adding a config to opt-out, it won't cause any issues.
