### ISSUE TITLE
fix: [xsl] project/website name (inside h2 tag) exposing project name from package.json without any ability to hide/change it

### ISSUE THREAD

**Issue by Irelynx** [nuxt-modules/sitemap#326]
### 🐛 The bug

While previewing `/sitemap.xml` from web-browser, project name from `package.json` file exposed to public user under `XML Sitemap` text (inside `<h2>` tag) as you can see on the screenshot:

![image](https://github.com/user-attachments/assets/ae959ad9-79f3-4171-9546-000d999341ca)

It is also impossible/unclear how one can change the name (without changing `package.json` and disabling `xsl` in nuxt config)
Project name exposed in "multiple sitemaps mode" as well on every sitemap page.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-lkegd2

### 🌈 Expected behavior

Project name from `package.json` shall not be exposed to public.
Project name could be added to configuration.

### ℹ️ Additional context

```
------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, nitro, site, sitemap
- Runtime Modules:  @nuxtjs/sitemap@5.3.5
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hi, the sitemap module will display your `site.name` within the XSL. 

If the name isn't the one you like, it's because it's falling [back to reading package.json](https://nuxtseo.com/site-config/getting-started/how-it-works) because you haven't defined one. You can define one by setting your site config name.

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  site: {
    url: 'https://example.com',
    name: 'My Awesome Website'
  },
})
```

If you don't want the name to appear at all you can [disable the XSL](https://nuxtseo.com/sitemap/guides/customising-ui#disabling-the-xls).

I understand this was missing from the sitemap docs so I've pushed up some improvements on the install page.
