### ISSUE TITLE
fix: link duplication

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/sitemap#333]
### 🐛 The bug

After updating to v6.0.0-beta.1 I have to make the following additions to let my testsuite pass, which look like duplicates of the already existing lines, but with swapped properties:

![image](https://github.com/user-attachments/assets/6d25423d-b44e-4cd1-853b-44e28fb0f7b7)

### 🛠️ To reproduce

https://github.com/dargmuesli/vio/actions/runs/10290667596/job/28481193061?pr=217

### 🌈 Expected behavior

There should be no additions for content that already exists, no matter the order of properties.

### ℹ️ Additional context

Could be that the issue is not with this module only, but maybe an incompatibility with another seo package. I can try to create a minimal reproduction if the issue's root is not immediately clear to you :green_heart:

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

I did some digging into your repo but I felt a bit lost on what the issue could be. I have tests specifically for nuxt generate with the i18n module and I don't have these duplicates 🤔 

If you have any time to make a [minimal reproduction](https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue) it would be super helpful, otherwise will revisit when I get a chance.

**Comment by dargmuesli** [comment]
Sure, I was looking through your tests as well for some time and was wondering the same. I just wanted to flag this real quick after updating the SEO tools in case a fix is obvious, but I can also dig deeper and provide a minimal reproduction when time allows.

**Comment by dargmuesli** [comment]
Some other update seems to have resolved the issue.

**Comment by harlan-zw** [comment]
FYI I was able to replicate this using Nuxt Content and Nuxt I18n and have pushed up a fix in the latest RC.
