### ISSUE TITLE
#internal/nitro/virtual/app-config is not defined in package

### ISSUE THREAD

**Issue by JhumanJ** [nuxt-modules/sitemap#374]
Hi there, same issue as https://github.com/nuxt/icon/issues/204 with this package. Fix seems to be here: https://github.com/nuxt/icon/pull/249

**Comment by JhumanJ** [comment]
Not very familiar with nitro, but looking af the PR fixing nuxt icon, it seems like the imports in [these files](https://github.com/search?q=repo%3Anuxt-modules%2Fsitemap+nitropack%2Fruntime&type=code) needs to be changed from `nitropack/runtime` to `#imports`. Sorry for not being able to push this further!

**Comment by JhumanJ** [comment]
Just realized that nuxt-content was a dependency of this, so the issue could just come from them: https://github.com/nuxt/content/issues/2736 https://github.com/nuxt/content/issues/2736

**Comment by saltytostitos** [comment]
I also have this problem as soon as adding @nuxtjs/sitemap as a nuxt module.
i went through every **nitropack** import and replaced with **#imports** ... and this didn't fix it. 
So I went through every dependency of sitemap that has a **nitropack** import and replaced with **#imports** and this did fixed it.

Not sure "which" change helped or if all were required to fix my problem.
sitemap
robots
nuxt-site-config
devtools-kit
@nuxt/kit

What's the best way to prevent doing this? 
bash makes this easy but where's the root cause of this?

**Comment by JhumanJ** [comment]
@harlan-zw I'd really appreciate if you could take a look

**Comment by harlan-zw** [comment]
Most likely related to the Site Config module trying to read config from the app config when it's not enabled for some reason.

If you have a reliable way to replicate it, it would help. I've never personally come across this.

**Comment by harlan-zw** [comment]
>  Works on github codespaces, not on several Macos computer we tested

I use linux :/

**Comment by harlan-zw** [comment]
I'm not able to replicate using Linux Mint.

v3 of the Nuxt Site Config module drops support for app config which may solve this, I'll have all of the modules updated to use this version shortly.
