### ISSUE TITLE
fix: Nuxt content and i18n missing links

### ISSUE THREAD

**Issue by Daandeve** [nuxt-modules/sitemap#389]
### 🐛 The bug

Nuxt content with nuxt i18n generates urls for only 1 language see the stackblitz. I also tried using `strictNuxtContentPaths: false` without any luck.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-yegumm1f?file=nuxt.config.ts

### 🌈 Expected behavior

The sitemap urls should be generated for all languages.

**Comment by harlan-zw** [comment]
The issue is that your nuxt content paths don't match your actual paths. You have the content prefixed with the locale in your content directory but then served without the locale prefix.

Either move the content dir for `nl` to without the prefix or manually set the paths within the md file, see https://stackblitz.com/edit/nuxt-starter-zmbrnfpr?file=content%2Fnews%2Ftest.md

**Comment by Daandeve** [comment]
When I add the prefix for all locales with the following config, the prefix is added for all pages. But the sitemap only displays the `en` paths
```
i18n: {
  strategy: 'prefix',
},
```
